"""contact details column

Revision ID: 716f03b0964a
Revises: b43ece36e460
Create Date: 2026-08-21 09:43:12.666721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716f03b0964a'
down_revision: Union[str, Sequence[str], None] = 'b43ece36e460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('contact_details', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'contact_details')
    # ### end Alembic commands ###
