"""Google Creds table

Revision ID: b43ece36e460
Revises: a8cb9d0e3602
Create Date: 2026-08-03 09:39:20.465132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43ece36e460'
down_revision: Union[str, Sequence[str], None] = 'a8cb9d0e3602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_token_encrypted', sa.String(length=2048), nullable=False),
    sa.Column('refresh_token_encrypted', sa.String(length=2048), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_credentials_user_id'), 'google_credentials', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_credentials_user_id'), table_name='google_credentials')
    op.drop_table('google_credentials')
    # ### end Alembic commands ###
