"""add contact activities

Revision ID: c9f93db4b45d
Revises: 33b080cb2ae8
Create Date: 2026-07-05 19:56:39.701617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f93db4b45d'
down_revision: Union[str, Sequence[str], None] = '33b080cb2ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('NOTE', 'CALL', 'EMAIL', 'MEETING', 'WHATSAPP', 'STATUS_CHANGED', 'FOLLOW_UP', name='activitytype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_activities_contact_id'), 'contact_activities', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_activities_created_at'), 'contact_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_contact_activities_type'), 'contact_activities', ['type'], unique=False)
    op.drop_index(op.f('idx_contacts_name_trgm'), table_name='contacts', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_contacts_name_trgm'), 'contacts', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_contact_activities_type'), table_name='contact_activities')
    op.drop_index(op.f('ix_contact_activities_created_at'), table_name='contact_activities')
    op.drop_index(op.f('ix_contact_activities_contact_id'), table_name='contact_activities')
    op.drop_table('contact_activities')
    # ### end Alembic commands ###
