"""add indexes

Revision ID: d2e7ebefbca2
Revises: f6703d669021
Create Date: 2026-06-29 09:38:55.557044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e7ebefbca2'
down_revision: Union[str, Sequence[str], None] = 'f6703d669021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contacts_last_contacted'), 'contacts', ['last_contacted'], unique=False)
    op.create_index(op.f('ix_contacts_name'), 'contacts', ['name'], unique=False)
    op.create_index(op.f('ix_contacts_next_followup'), 'contacts', ['next_followup'], unique=False)
    op.create_index(op.f('ix_contacts_source'), 'contacts', ['source'], unique=False)
    op.create_index(op.f('ix_contacts_status'), 'contacts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_status'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_source'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_next_followup'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_last_contacted'), table_name='contacts')
    # ### end Alembic commands ###
